- hosts: terraform-ansible
  tasks:
  - name: Install python3, virtualenv
    apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
    become: yes
  - name: Install PIP dependencies Django and Django Rest
    pip: 
        virtualenv: /home/ubuntu/tcc/venv
        name:
                - django
                - djangorestframework
  - name: Starting project
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc' 
  - name: Change hosts settings
    lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes
 
  # tasks:
  #  - name: create file
  #    copy:
  #     dest: /home/ubuntu/index.html
  #     content: <h1>Created with Terraform and Ansible</h1>
  #  - name: create server
  #    shell: "nohup busybox httpd -f -p 8080 &"

